spring:
  application:
    name: ticket-app
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    # url: jdbc:h2:mem:testdb
    url: jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: Root#123*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8085
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  auth:
    secret: HDG1204#HJSHSOIUSYGH$SGSS*-SD@!@IU